### PR TITLE
feat(composer): add php 8.2 support

### PR DESCRIPTION
**Pull request by duboiss**

### CODE REVIEW

**Comment by duboiss** [comment]
Hey @grzegorz-jamroz can you check this PR please, thanks

**Comment by duboiss** [comment]
Update of its old PR, ping @Rayn93 thanks

**Comment by Rayn93** [comment]
Hi @duboiss 
Sorry for delay with this topic (I hadn't got active notification for this repo).

New release with support for PHP8.2 and PHP8.3 is already released:
https://github.com/FACT-Finder-Web-Components/php-communication-sdk/releases/tag/v0.9.8

**Comment by duboiss** [comment]
Thanks @Rayn93 
Can you add the support on this package not updated since 1 year please ? https://github.com/FACT-Finder-Web-Components/magento2-module

**Comment by Rayn93** [comment]
@duboiss 
Please use v4 of this SDK: https://github.com/FACT-Finder-Web-Components/magento2-module/tree/release/4.x
Support for PHP8.2 will be implemented soon.

**Pull request closed without merging**
